config/routes.rb
Rails.application.routes.draw do

  get 'list_transactions' => 'appointments#list_transactions'
  post 'create_appointment' => 'appointments#create_appointment'
  get 'accept_appointment' => 'appointments#accept_appointment'
  get 'decline_appointment' => 'appointments#decline_appointment'
  get 'cancel_appointment' => 'appointments#cancel_appointment'
  get 'appointment_time_sheet' => 'appointments#appointment_time_sheet'
  get 'close_appointment_time_sheet' => 'appointments#close_appointment_time_sheet'
  post 'apt_time_display' => 'appointments#apt_time_display'
  post 'selected_time' => 'appointments#selected_time'
  post 'unselected_time' => 'appointments#unselected_time'
  post 'selectable_time' => 'appointments#selectable_time'

  post 'stripe_webhook' => 'appointments#stripe_webhook'
  get 'slack_webhook' => 'appointments#slack_webhook'
  get 'verify' => 'appointments#verify'

  get 'set_date_available' => 'available_days#set_date_available'
  get 'set_date_unavailable' => 'available_days#set_date_unavailable'
  get 'time_sheet' => 'available_days#time_sheet'
  get 'close_time_sheet' => 'available_days#close_time_sheet'
  get 'set_time_unavailable' => 'available_days#set_time_unavailable'
  get 'set_time_available' => 'available_days#set_time_available'

  resources :tasks do
    get 'add_selected' => 'tasks#add_selected'
    get 'remove_selected' => 'tasks#remove_selected'
  end

  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'
  resources :blog
  get '/password_input' => 'blog#password_input'
  post '/password_authenticate' => 'blog#password_authenticate'
  get '/end_session' => 'blog#end_session'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'welcome/index'
  resources :sessions
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users do
    resources :appointments, shallow: true
    resources :reviews,shallow: true
    resources :available_days, shallow: true do
      resources :available_times, shallow: true
    end
    resources :conversations, shallow: true do
     resources :messages
  end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'cities/:state', to: 'application#cities'

  get '/assesment' => 'users#assesment'

  get '/companion' => 'welcome#be_a_comp'

  get '/super_adult' => 'welcome#need_a_comp'

  get '/sen_new' => 'users#sen_new'

  get '/main_sen' => 'users#main_sen'

  get 'guard_sen' => 'users#guard_sen'

  get '/comp_new' => 'users#comp_new'

  get '/comp_test' => 'users#comp_test'

  get '/privacy_policy' => 'welcome#privacy_policy'

  get '/terms_of_services' => 'welcome#terms_of_services'

  get '/cookie_policy' => 'welcome#cookie_policy'

  get '/payment_policy' => 'welcome#payment_policy'

  get '/comp_request' => 'appointments#comp_request'

  get '/login' => 'sessions#new'

  post  '/login' => 'sessions#create'

  get '/logout', to: 'sessions#destroy'

  get '/about' => 'welcome#team'

  root 'welcome#index'

end

app/models/task.rb
class Task < ApplicationRecord
  has_many :join_users_tasks, dependent: :destroy
  has_many :users, through: :join_users_tasks, dependent: :destroy
  belongs_to :service
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @user = User.find(params[:user_id])
    end

    def add_selected
        task_id = params[:task_id]
        User.find(params[:user_id]).tasks << Task.all[task_id.to_i - 1]
        @user = User.find(params[:user_id])
        respond_to do |format|
            format.html { redirect_to user_path(@user) }
            format.js { render :index, :locals => {:user_id => params[:user_id], :task_id => params[:task_id]} }
        end
    end

    def remove_selected
        task_id = params[:task_id]
        User.find(params[:user_id]).tasks.destroy(task_id.to_i)
        @user = User.find(params[:user_id])
        respond_to do |format|
            format.html { redirect_to user_path(@user) }
            format.js { render :index, :locals => {:user_id => params[:user_id], :task_id => params[:task_id]} }
        end
    end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_index.html.erb
    <div id='sen_services_ajax' class='container'>
        <button class="collapsible">
          <h3 id='service_header'>
            <% if @user.identification == "Senior" %>
              Services Required
            <% else %>
              Services Offered
            <% end %>
          </h3>
          <i class="fa fa-angle-down task-arrow" style="display:none"></i>
          <i class="fa fa-angle-up task-arrow" style="display:block"></i>
        </button>
        <div class="task-content">
          <% Service.all.each do |service|%><!-- List all Service Categories -->
            <div class='sen_service_section container'>
              <h3 id='service_name'><%= service.name %></h3>
              <div class='sen_service_tasks container'>
                <% service.tasks.each do |task| %><!-- Display all Tasks by Service category -->
                <!-- DEVELOPERS: There is a whitespace character between the symbol and the name of the task. Leave it alone :) -->
                  <% if task.user_ids.include? @user.id %>
                      <%= link_to task_remove_selected_path( user_id: @user.id, task_id: task.id ), id: 'remove_task_button', class: 'all_tasks', method: 'GET', remote: true do %>
                        <p id='task_name'><%= task.name %></p>
                        <i class="fa fa-times"></i>
                      <% end %>
                  <% else %>
                    <%= link_to task_add_selected_path( user_id: @user.id, task_id: task.id ), id: 'add_task_button', class: 'all_tasks', method: 'GET', remote: true do %>
                        <p id='task_name'><%= task.name %></p>
                    <% end %>
                  <% end %>
                <% end %>
               </div>
            </div>
          <% end %>
          <button id="done_button">Close</button>
        </div>
    </div>

app/views/tasks/_save.js.erb
$(".sen_services").html("<%= escape_javascript(render 'tasks/index') %>")

app/views/tasks/index.js.erb
$("#sen_services_ajax").remove()
$("<%=j render :partial => 'index' %>").appendTo('#sen_services_tasks_container')