config/routes.rb
Rails.application.routes.draw do

  get 'list_transactions' => 'appointments#list_transactions'
  post 'create_appointment' => 'appointments#create_appointment'
  get 'accept_appointment' => 'appointments#accept_appointment'
  get 'decline_appointment' => 'appointments#decline_appointment'
  get 'cancel_appointment' => 'appointments#cancel_appointment'
  get 'appointment_time_sheet' => 'appointments#appointment_time_sheet'
  get 'close_appointment_time_sheet' => 'appointments#close_appointment_time_sheet'
  post 'apt_time_display' => 'appointments#apt_time_display'
  post 'selected_time' => 'appointments#selected_time'
  post 'unselected_time' => 'appointments#unselected_time'
  post 'selectable_time' => 'appointments#selectable_time'

  post 'stripe_webhook' => 'appointments#stripe_webhook'
  get 'slack_webhook' => 'appointments#slack_webhook'
  get 'verify' => 'appointments#verify'

  get 'set_date_available' => 'available_days#set_date_available'
  get 'set_date_unavailable' => 'available_days#set_date_unavailable'
  get 'time_sheet' => 'available_days#time_sheet'
  get 'close_time_sheet' => 'available_days#close_time_sheet'
  get 'set_time_unavailable' => 'available_days#set_time_unavailable'
  get 'set_time_available' => 'available_days#set_time_available'

  resources :tasks do
    get 'add_selected' => 'tasks#add_selected'
    get 'remove_selected' => 'tasks#remove_selected'
  end

  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'
  resources :blog
  get '/password_input' => 'blog#password_input'
  post '/password_authenticate' => 'blog#password_authenticate'
  get '/end_session' => 'blog#end_session'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'welcome/index'
  resources :sessions
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users do
    resources :appointments, shallow: true
    resources :reviews,shallow: true
    resources :available_days, shallow: true do
      resources :available_times, shallow: true
    end
    resources :conversations, shallow: true do
     resources :messages
  end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'cities/:state', to: 'application#cities'

  get '/assesment' => 'users#assesment'

  get '/companion' => 'welcome#be_a_comp'

  get '/super_adult' => 'welcome#need_a_comp'

  get '/sen_new' => 'users#sen_new'

  get '/main_sen' => 'users#main_sen'

  get 'guard_sen' => 'users#guard_sen'

  get '/comp_new' => 'users#comp_new'

  get '/comp_test' => 'users#comp_test'

  get '/privacy_policy' => 'welcome#privacy_policy'

  get '/terms_of_services' => 'welcome#terms_of_services'

  get '/cookie_policy' => 'welcome#cookie_policy'

  get '/payment_policy' => 'welcome#payment_policy'

  get '/comp_request' => 'appointments#comp_request'

  get '/login' => 'sessions#new'

  post  '/login' => 'sessions#create'

  get '/logout', to: 'sessions#destroy'

  get '/about' => 'welcome#team'

  root 'welcome#index'

end

app/models/available_day.rb
class AvailableDay < ApplicationRecord
  belongs_to :user
  has_many :available_times, dependent: :destroy
end

app/controllers/available_days_controller.rb
# DEVELOPER NOTES:
# Some routes are left in place as possible HTML only browsers may need them until we update the newer routes.
class AvailableDaysController < ApplicationController
  def index
  end

  def set_date_unavailable
    # Set Date as Unavailable.
    @availableDay = AvailableDay.where({ user_id: current_user.id, date: params[:available_day][:date] })
    AvailableDay.destroy(@availableDay[0].id)
  end

  def set_date_available
    # Set Date as Available.
    @available_day = AvailableDay.create(available_days_params)
  end

  def time_sheet
    # Opens specific dates Timesheet
    @availableDay = AvailableDay.where({user_id:current_user, date: available_days_params[:date]})
    @all_times = ["07:00AM","08:00AM","09:00AM","10:00AM","11:00AM","12:00PM","01:00PM","02:00PM","03:00PM","04:00PM","05:00PM","06:00PM","07:00PM"]
  end

  def close_time_sheet
    # Close Time Sheet
  end

  def set_time_unavailable
    # Set Time as Unavailable.
  end

  def set_time_available
    # Set Time as Available.
  end

  def new # Replaced with 'set_date_available'
    @user = current_user
    @available_day = AvailableDay.new
    @current_date = current_user.available_days
    @availableDay = @current_date.where('user_id = current_user','date=date')
  end

  def create # Replaced with 'set_date_available' & 'set_date_unavailable'
    @availableDay = AvailableDay.where('date = ? AND user_id = ?', available_days_params[:date], available_days_params[:user_id])
    if @availableDay.length >= 1
      @deldate = @availableDay[0]
      @availableDay[0].destroy
      respond_to do |format|
        format.html {redirect_to new_user_available_day_path(@user)}
        format.js {render 'new_del'}
      end
    elsif @availableDay.length <= 1
      @availableDay = AvailableDay.create(available_days_params)
      respond_to do |format|
        format.html {redirect_to new_user_available_day_path(@user)}
        format.js {render 'new'}
      end
    else
      redirect_to "new"
    end
  end

  def edit

  end

  def update
    @availableDay = AvailableDay.find(params[:id])
    @time = @availableDay.available_times.where('time = ? ', params[:time])
    if @time.length >= 1
      @show_del = @time[0].time.strftime('%I%p')
      @real_show_del = @time[0].time.strftime('%I:%M%p')
      @time[0].destroy
      respond_to do |format|
        format.html {redirect_to available_day_path(available_day:{date: @availableDay.date,user_id: current_user.id,comment: 'I am ready'},id: @availableDay.id)}
        format.js {render 'show_del'}
      end
    else
      @time = @availableDay.available_times.new(time: params[:time])
      if @time.save
        @real_time = @time.time.strftime('%I:%M%p')
        @time = @time.time.strftime('%I%p')
        respond_to do |format|
          format.html {redirect_to available_day_path(available_day:{date: @availableDay.date,user_id: current_user.id,comment: 'I am ready'},id: @availableDay.id)}
          format.js {render 'show'}
        end
      end
    end
  end

  def show
    @availableDay = AvailableDay.where({user_id:current_user,date: available_days_params[:date]})
    @arr = ["07:00AM","08:00AM","09:00AM","10:00AM","11:00AM","12:00PM","01:00PM","02:00PM","03:00PM","04:00PM","05:00PM","06:00PM","07:00PM"]
    @checkdate = @availableDay[0].try(:date)
    if(@availableDay.present?)
      @next_date =  AvailableDay.where({user_id:current_user}).where("date>?",@availableDay[0].date).order("date ASC").limit(1).first.try(:date)
      @prev_date =  AvailableDay.where({user_id:current_user}).where("date<?",@availableDay[0].date).order("date DESC").limit(1).first.try(:date)
    end
    @last_date = current_user.available_days.order('ASC')
    @first_date = current_user.available_days.order('ASC')
  end

  def destroy # Replaced with 'set_date_unavailable'
    @availableDay = AvailableDay.where({user_id:current_user,date: params[:id]})
    @availableDay[0].destroy
    redirect_to new_user_available_day_path(current_user)
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  private
  def available_days_params
    params.require(:available_day).permit(:user_id, :comment, :date)
  end
end

app/helpers/available_days_helper.rb
module AvailableDaysHelper
  def aval(user1, user2)
    user1_dates = []
    user1.available_days.each do |day|
      if day.date >= Date.today
        user1_dates.push(day.date)
      end
    end

    user2_dates = []
    user2.available_days.each do |day|
      if day.date >= Date.today
        user2_dates.push(day.date)
      end
    end

    date_match = user1_dates & user2_dates
    date_match.sort
  end

  def aval_time(user1,user2,date)
    x = []
    y = []
    time_one = []
    time_two = []
      x = user1.available_days.where(date: date)
      y = user2.available_days.where(date: date)
      # Just concatenate instead of going through each
    if x.length != 0 && y.length != 0
       x[0].available_times.each do |time|
        time_one.push(time.time)
      end
       y[0].available_times.each do |time|
        time_two.push(time.time)
      end
    end
    final_time = time_one & time_two
  end

  def date_exit(user)
    dates = []
    user.available_days.each do |day|
      dates.push(day.date)
    end
    dates
  end

  def stripoff(available_day)
    convert = []
    available_day.available_times.each do |time|
      convert.push(time.time.strftime('%I:%M%p'))
    end
     convert
  end

  def app_time(user,available_day)
    app_date = user.companions.where("start_date = ?", available_day.date)
      if app_date.size >= 1
      app_work =  AvailableDay.where("date = ?",app_date[0].start_date)
      final = []
      app_work[1].available_times.each do |time|
        final.push(time.time.strftime('%I:%M%p'))
      end
       final
      end
  end
end

app/views/available_days/_calendar.html.erb
<div id='calendar_ajax_remove' class="row" style="padding-left: 15px; padding-right: 15px;">
  <!-- This IF statement dictates if the calander shown is this or next months based on a passed local. As of Rails 5.1.4 an error requires "local_assigns" to find the actual passed local. This can be removed at a later time. -->
    <% if local_assigns[:next_month] == "next" %>
      <% set_of_dates = (Date.today.beginning_of_month.next_month..Date.today.at_end_of_month.next_month) %>
    <% else %>
      <% set_of_dates = (Date.today.beginning_of_month..Date.today.at_end_of_month) %>
    <% end %>

  <% set_of_dates.each do |date| %>
    <div class="col-lg-2 col-md-2 col-2 form_div cal_pad">
      <!-- If date is prior to current date -->
      <!-- [Clicking: Does nothing] -->
        <% if Date.today > date %>
          <div class="btn days_cal_but" style="background-color: gray;">
            <!-- Display Day (name) of the Week -->
            <p class="notification work_p"><%= date.to_time.strftime('%a') %></p>
            <!-- Display Date (number) of the Week -->
            <p class="notification work_p"><%= date.to_time.strftime('%d') %></p>
          </div>
      <!-- If User is a Senior and has an Appointment on this date -->
      <!-- [Clicking: Cancels Appointment & Sets Day as Unavailable ] -->
        <% elsif sendays(current_user).include?(date) && date_exit(current_user).include?(date) %>
          <% appointment = @appointments.find {|appointment| appointment.start_date == date && appointment.senior_id == current_user.id && appointment.accept == true} %>
          <% if appointment != nil %>
            <%= link_to cancel_appointment_path(user_id: current_user, appointment_id: appointment.id), id: "cancel_appointment_#{appointment.id}" do %>
              <div class="btn days_cal_but" style="background-color: green;">
                <!-- Display Day (name) of the Week -->
                <p class="notification work_p"><%= date.to_time.strftime('%a') %></p>
                <!-- Display Date (number) of the Week -->
                <p class="notification work_p"><%= date.to_time.strftime('%d') %></p>
              </div>
            <% end %>
            <div id="set_times_tab_<%= date %>" class="set_times_tab">
              <!-- There is an invisible character below  -->
              　
            </div>
          <% end %>
      <!-- If User is a Companion and has an Appointment on this date -->
      <!-- [Clicking: Cancels Appointment & Sets Day as Unavailable ] -->
        <% elsif appdays(current_user).include?(date) && date_exit(current_user).include?(date) %>
          <% appointment = @appointments.find {|appointment| appointment.start_date == date && appointment.companion_id == current_user.id && appointment.accept == true} %>
          <% if appointment != nil %>
          <div id="set_date_append_<%= date %>">
            <%= link_to cancel_appointment_path(user_id: current_user, appointment_id: appointment.id), id: "cancel_appointment_#{date}", remote: true do %>
              <div class="btn days_cal_but" style="background-color: green;">
                <!-- Display Day (name) of the Week -->
                <p class="notification work_p"><%= date.to_time.strftime('%a') %></p>
                <!-- Display Date (number) of the Week -->
                <p class="notification work_p"><%= date.to_time.strftime('%d') %></p>
              </div>
            <% end %>
            <div id="set_times_tab_<%= date %>" class="set_times_tab">
              <!-- There is an invisible character below  -->
              　
            </div>
          <% end %>
        </div>
      <!-- User has set day as Available for an Appointment -->
      <!-- [Clicking: Sets date as Unavailable for Appointments] -->
      <!-- {This route will use the "accepted.js.erb" format} -->
        <%  elsif date_exit(current_user).include?(date) %>
          <div id="set_date_append_<%= date %>">
            <%= link_to set_date_unavailable_path(current_user, date: date,  available_day: {date: date, comment: "I am ready", user_id: current_user.id}), id: "set_date_remove_#{date}", remote: true do %>
              <div class="btn days_cal_but" style="background-color: orange;">
                <!-- Display Day (name) of the Week -->
                <p class="notification work_p"><%= date.to_time.strftime('%a') %></p>
                <!-- Display Date (number) of the Week -->
                <p class="notification work_p"><%= date.to_time.strftime('%d') %></p>
              </div>
            <% end %>
            <div id="set_times_tab_<%= date %>" class="set_times_tab">
              <%= link_to 'Set Times', time_sheet_path(current_user, date: date, available_day: {date: date, comment: "I am ready", user_id: current_user.id}), id: "open_sheet_#{date}", class: "open_sheet", remote: true %>
            </div>
          </div>
      <!-- Date has not been set as Available for Appointments by User -->
      <!-- [Clicking: Sets date as Available for Appointments] -->
        <% else %>
          <div id="set_date_append_<%= date %>">
            <%= link_to set_date_available_path(current_user, date: date,  available_day: {date: date, comment: "I am ready", user_id: current_user.id}), id: "set_date_remove_#{date}", remote: true do %>
              <div class="btn days_cal_but" style="background-color: white;">
                <!-- Display Day (name) of the Week -->
                <p class="notification work_p"><%= date.strftime('%a') %></p>
                <!-- Display Date (number) of the Week -->
                <p class="notification work_p"><%= date.strftime('%d') %></p>
              </div>
            <% end %>
            <div id="set_times_tab_<%= date %>" class="set_times_tab">
              <!-- There is an invisible character below  -->
              　
            </div>
          </div>
        <% end %><!-- End of individual date categorization -->
    </div>
  <% end %><!-- End of ALL dates loop -->
</div>

app/views/available_days/_cancelled.html.erb
<!-- This is an unused view, but it is required for cancelled.js.erb to work -->

app/views/available_days/_declined.html.erb
<!-- This is an unused view, but it is required for declined.js.erb to work -->

app/views/available_days/_set_date_available.html.erb
<% if @selected_appointment != nil %>
  <% date = @selected_appointment.start_date %>
  <% appointment = @selected_appointment %>
<% else %>
  <% date = params[:date] %>
<% end %>
  <%= link_to set_date_unavailable_path(current_user, date: date,  available_day: {date: date, comment: "I am ready", user_id: current_user.id}), id: "set_date_remove_#{date}", remote: true do %>
    <div class="btn days_cal_but" style="background-color: orange;">
      <!-- Display Day (name) of the Week -->
      <p class="notification work_p"><%= date.to_time.strftime('%a') %></p>
      <!-- Display Date (number) of the Week -->
      <p class="notification work_p"><%= date.to_time.strftime('%d') %></p>
    </div>
  <% end %>
  <div id="set_times_tab_<%= date %>" class="set_times_tab">
    <%= link_to 'Set Times', time_sheet_path(current_user, date: date, available_day: {date: date, comment: "I am ready", user_id: current_user.id}), id: "open_sheet_#{date}", class: "open_sheet", remote: true %>
  </div>

app/views/available_days/_set_date_complete.html.erb
<% date = @selected_appointment.start_date %>
<% appointment = @selected_appointment %>
<%= link_to cancel_appointment_path(user_id: current_user, appointment_id: appointment.id), id: "cancel_appointment_#{date}", remote: true do %>
  <div class="btn days_cal_but" style="background-color: green;">
    <!-- Display Day (name) of the Week -->
    <p class="notification work_p"><%= date.to_time.strftime('%a') %></p>
    <!-- Display Date (number) of the Week -->
    <p class="notification work_p"><%= date.to_time.strftime('%d') %></p>
  </div>
<% end %>

app/views/available_days/_show.html.erb
<button class="btn t_cal_but" style="background-color: red;">
  <%= @real_time%>
</button>

app/views/available_days/accepted.js.erb
// Companion Popup Update:
    $('#appointment_pop_up_ajax_remove_<%= @selected_appointment.id %>').remove()

// Calendar Update:
    // Remove "set time" option for the now complete date
        $('#set_times_tab_<%= @selected_appointment.start_date %>').remove()
    // Remove html button for canceling(declining) appointment
        $('#set_date_remove_<%= @selected_appointment.start_date %>').remove()
    // Append partial complete(green) to containing element
        $("<%=j render :partial => 'available_days/set_date_complete' %>").appendTo("#set_date_append_<%= @selected_appointment.start_date %>")

    // Removes "accept/decline" section for the now "complete" section:
    // Removes the accept/decline buttons and replaces with a cancel button.
    // Changes 'PENDING' to 'ACCEPTED' in the appointment status field.
    $('#appointment_status_div_<%= @selected_appointment.id %>').empty();
    $('#appointment_status_div_<%= @selected_appointment.id %>').append(
      '<p>Appointment Status: <span class="accepted">ACCEPTED</span></p>'
    );
    $('#appointment_buttons_append_remove_<%= @selected_appointment.id %>').empty();
    $('#appointment_buttons_append_remove_<%= @selected_appointment.id %>').append(
           '<%= link_to 'Cancel Appointment', cancel_appointment_path(user_id: current_user, appointment_id: @selected_appointment.id), id: "cancel_appointment_#{@selected_appointment.id}", class: "cancel_appointment_button", remote: true %>');

app/views/available_days/calendar.js.erb
$("#calendar_ajax_remove").remove()
$("<%=j render :partial => 'calendar' %>").appendTo('#calendar_ajax_append')

app/views/available_days/cancelled.js.erb
// Companion Popup Update:
    $('#appointment_pop_up_ajax_remove_<%= @selected_appointment.id %>').remove()

// Calendar Update:
    // Remove "set time" option for the now declined date
        $('#set_times_tab_<%= @selected_appointment.start_date %>').remove()
    // Remove html button for cancelling appointment
        $('#cancel_appointment_<%= @selected_appointment.start_date %>').remove()
    // Append partial unavailable(white) to containing element
        $("<%=j render :partial => 'available_days/set_date_unavailable' %>").appendTo("#set_date_append_<%= @selected_appointment.start_date %>")

    // Cancels the selected appointment. Removes the appointment from the DOM.
    $('#appointment_view_remove_<%= @selected_appointment.id %>').fadeOut(400, function() {
      $('#appointment_view_remove_<%= @selected_appointment.id %>').remove();
      $("#appointment_<%= @selected_appointment.id %>_info").remove();
      $("#horizontal_rule_remove_<%= @selected_appointment.id %>").remove();
    });

app/views/available_days/close_time_sheet.js.erb
<% date = params[:date] %>
// $("#time_sheet_<%= date %>").remove()
$(".time_sheet_overlay").remove()

app/views/available_days/set_date_unavailable.js.erb
<% date = params[:date] %>
$("#set_times_tab_<%= date %>").remove()
$("#set_date_remove_<%= date %>").remove()
$("<%=j render :partial => 'set_date_unavailable' %>").appendTo('#set_date_append_<%= date %>')

app/views/available_days/show.js.erb
$("#<%=@time%>").html("<%=escape_javascript(render 'show')%>");

app/views/available_days/show_del.js.erb
$("#<%=@show_del%>").html("<%=escape_javascript(render 'show_del')%>");

app/views/available_days/time_sheet.js.erb
<% date = params[:date]%>
$("<%=j render :partial => 'time_sheet' %>").appendTo('#overlay_container').hide().fadeIn(1000)