config/routes.rb
Rails.application.routes.draw do

  get 'list_transactions' => 'appointments#list_transactions'
  post 'create_appointment' => 'appointments#create_appointment'
  get 'accept_appointment' => 'appointments#accept_appointment'
  get 'decline_appointment' => 'appointments#decline_appointment'
  get 'cancel_appointment' => 'appointments#cancel_appointment'
  get 'appointment_time_sheet' => 'appointments#appointment_time_sheet'
  get 'close_appointment_time_sheet' => 'appointments#close_appointment_time_sheet'
  post 'apt_time_display' => 'appointments#apt_time_display'
  post 'selected_time' => 'appointments#selected_time'
  post 'unselected_time' => 'appointments#unselected_time'
  post 'selectable_time' => 'appointments#selectable_time'

  post 'stripe_webhook' => 'appointments#stripe_webhook'
  get 'slack_webhook' => 'appointments#slack_webhook'
  get 'verify' => 'appointments#verify'

  get 'set_date_available' => 'available_days#set_date_available'
  get 'set_date_unavailable' => 'available_days#set_date_unavailable'
  get 'time_sheet' => 'available_days#time_sheet'
  get 'close_time_sheet' => 'available_days#close_time_sheet'
  get 'set_time_unavailable' => 'available_days#set_time_unavailable'
  get 'set_time_available' => 'available_days#set_time_available'

  resources :tasks do
    get 'add_selected' => 'tasks#add_selected'
    get 'remove_selected' => 'tasks#remove_selected'
  end

  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'
  resources :blog
  get '/password_input' => 'blog#password_input'
  post '/password_authenticate' => 'blog#password_authenticate'
  get '/end_session' => 'blog#end_session'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'welcome/index'
  resources :sessions
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users do
    resources :appointments, shallow: true
    resources :reviews,shallow: true
    resources :available_days, shallow: true do
      resources :available_times, shallow: true
    end
    resources :conversations, shallow: true do
     resources :messages
  end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'cities/:state', to: 'application#cities'

  get '/assesment' => 'users#assesment'

  get '/companion' => 'welcome#be_a_comp'

  get '/super_adult' => 'welcome#need_a_comp'

  get '/sen_new' => 'users#sen_new'

  get '/main_sen' => 'users#main_sen'

  get 'guard_sen' => 'users#guard_sen'

  get '/comp_new' => 'users#comp_new'

  get '/comp_test' => 'users#comp_test'

  get '/privacy_policy' => 'welcome#privacy_policy'

  get '/terms_of_services' => 'welcome#terms_of_services'

  get '/cookie_policy' => 'welcome#cookie_policy'

  get '/payment_policy' => 'welcome#payment_policy'

  get '/comp_request' => 'appointments#comp_request'

  get '/login' => 'sessions#new'

  post  '/login' => 'sessions#create'

  get '/logout', to: 'sessions#destroy'

  get '/about' => 'welcome#team'

  root 'welcome#index'

end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  self.per_page = 10
  mount_uploader :image, BlogImageUploader

  scope :next, lambda {|id| where("id > ?",id).order("id ASC") } # this is the default ordering for AR
  scope :previous, lambda {|id| where("id < ?",id).order("id DESC") }

  def next
    Blog.next(self.id).first
  end

  def previous
    Blog.previous(self.id).first
  end


end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def index
    @blogs = Blog.paginate(:page => params[:page], :per_page => 15).order("created_at DESC")
  end

  def show
    @blog = Blog.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
    redirect_to :blog_index, alert: 'Blog not found'
  end

  def password_input
  end

  def password_authenticate
    if params[:input][:password] == ENV["BLOG_PASSWORD"]
      session[:admin] = true
      redirect_to :blog_index
    else
      flash[:failure] = "Please try again."
      redirect_to :password_input
    end
  end

  def end_session
    session[:admin] = false
    redirect_to :blog_index
  end

  def new
    if session[:admin]
      @blog = Blog.new
    else
      redirect_to password_input_path
    end
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      flash[:success] = "Blog created succesfully."
      redirect_to @blog
    else
      flash[:success] = "Blog needs more information."
      redirect_to new_blog_path
    end
  end

  def edit
    if session[:admin]
      @blog = Blog.find(params[:id])
    else
      redirect_to password_input_path
    end
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update_attributes(blog_params)
      flash[:success] = "Blog succesfully updated."
      redirect_to @blog
    else
      flash[:success] = "Blog needs more information."
      redirect_to edit_blog_path
    end
  end

  def destroy
    if session[:admin]
      Blog.find(params[:id]).destroy
      flash[:success] = "Blog succesfully deleted."
      redirect_to :blog_index
    else
      redirect_to password_input_path
    end

  end

  private
    def blog_params
      params.require(:blog).permit(:title, :body, :image)
    end

end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/_social.html.erb
<div class='blog_social_media'>
  <!-- Amazing resource: https://github.com/bradvin/social-share-urls -->
  <% @social_media_title = @blog.title.gsub!(/(<[^>]*>)|\n|\t/s) {" "} %>
  <% @social_media_summary = @blog.body.gsub!(/(<[^>]*>)|\n|\t/s) {" "} %>
  <%# @social_media_url = "http://localhost:3000/blog/#{@blog.id}" %>
  <% @social_media_url = "https://senyours.io/blog/#{@blog.id}" %>
  <% @social_media_domain = "senyours.io" %>
  <script async defer src="//assets.pinterest.com/js/pinit.js"></script>
  <% if @blog.image? %>
  <img class='hidden_pinterest_image' src="<%=@blog.image.large%>" alt="Pinterest_Image" data-pin-description="<%= @social_media_title %>" >
  <% else %>
  <img class='hidden_pinterest_image' src="/assets/findyou.jpg" alt="Pinterest_Image" data-pin-description="<%= @social_media_title %>" >
  <% end %>

  <!-- LinkedIn -->
  <%= link_to "http://www.linkedin.com/shareArticle?mini=true&url=#{@social_media_url}&title=#{@social_media_title}&summary=#{@social_media_summary}&source=#{@social_media_domain}", target: :_blank, :class => 'blog_social_media_link' do %>
    <%= image_tag("social/linkedin.png", :alt => "Social_Media_LinkedIn_Image", :class => "blog_social_media_image", 'data-pin-nopin' => "true") %>
  <% end %>

  <!-- Twitter -->
  <%= link_to "http://twitter.com/intent/tweet?status=#{@social_media_title}+#{@social_media_url}", target: :_blank, :class => 'blog_social_media_link' do %>
    <%= image_tag("social/twitter.png", :alt => "Social_Media_Twitter_Image", :class => "blog_social_media_image", 'data-pin-nopin' => "true") %>
  <% end %>

  <!-- Facebook -->
  <%= link_to "http://www.facebook.com/sharer/sharer.php?u=#{@social_media_url}&title=#{@social_media_title}", target: :_blank, :class => 'blog_social_media_link' do %>
    <%= image_tag("social/facebook.png", :alt => "Social_Media_Facebook_Image", :class => "blog_social_media_image", 'data-pin-nopin' => "true") %>
  <% end %>

  <!-- Pinterest -->
  <%= link_to "https://www.pinterest.com/pin/create/button/", target: :_blank, 'data-pin-do' => `buttonBookmark`, 'data-pin-custom' => 'true', 'data-pin-url' => "#{@social_media_url}", :class => 'blog_social_media_link' do %>
    <%= image_tag("social/pinterest.png", :alt => "Social_Media_Pinterest_Image", :class => "blog_social_media_image", 'data-pin-nopin' => "true") %>
  <% end %>

  <!-- Google+ -->
  <%= link_to "https://plus.google.com/share?url=#{@social_media_url}&text=#{@social_media_title}", target: :_blank, :class => 'blog_social_media_link' do %>
    <%= image_tag("social/google.plus.png", :alt => "Social_Media_Google+_Image", :class => "blog_social_media_image", 'data-pin-nopin' => "true") %>
  <% end %>

  <!-- Reddit -->
  <%= link_to "https://reddit.com/submit?url=#{@social_media_url}&title=#{@social_media_title}", target: :_blank, :class => 'blog_social_media_link' do %>
    <%= image_tag("social/reddit.png", :alt => "Social_Media_Reddit_Image", :class => "blog_social_media_image", 'data-pin-nopin' => "true") %>
  <% end %>

  <!-- Digg -->
  <%= link_to "http://www.digg.com/submit?url=#{@social_media_url}", target: :_blank, :class => 'blog_social_media_link' do %>
    <%= image_tag("social/digg.png", :alt => "Social_Media_Digg_Image", :class => "blog_social_media_image", 'data-pin-nopin' => "true") %>
  <% end %>

  <!-- Email -->
  <%= link_to "mailto:?subject=#{@social_media_title}&body=#{@social_media_url}%0D%0A%0D%0A#{@social_media_summary}", target: :_blank, :class => 'blog_social_media_link' do %>
    <%= image_tag("social/gmail.png", :alt => "Social_Media_Email_Image", :class => "blog_social_media_image", 'data-pin-nopin' => "true") %>
  <% end %>

</div>

app/views/blog/edit.html.erb
<script src="https://cdn.ckeditor.com/ckeditor5/10.0.1/classic/ckeditor.js"></script>
<!-- Resources for ckeditor -->
<!-- http://www.dailysmarty.com/posts/how-to-integrate-ckeditor-into-a-rails-5-application -->
<!-- https://github.com/galetahub/ckeditor -->

<div id="edit_blog_form_container">
  <h1>Update Blog Post:</h1>
  <div id="edit_blog_form">
      <%= form_for @blog, url: {action: "update"} do |f| %>
          <div id='edit_blog_form_section'>
            <%= f.label :image %>
            <%= f.file_field :image %>
            <p>Images should be 1200 x 400 at minimum to prevent blurryness.</p>
          </div>
          <div id='edit_blog_form_section'>
              <%= f.label :title %>
              <%= f.cktext_area :title, value: @blog.title %>
          </div>
          <div id='edit_blog_form_section'>
            <%= f.label :body %>
            <%= f.cktext_area :body, value: @blog.body %>
          </div>
          <div id='edit_blog_form_section'>
              <%= f.submit "Edit post", id: "edit_blog_form_button" %>
          </div>
      <% end %>
  </div>
</div>

<script>
  ClassicEditor
    .create( document.querySelector( '#editor' ) )
    .catch( error => {
        console.error( error );
  } );
</script>

app/views/blog/index.html.erb
<body style="background-color: #f6f6f6;">
  <div id="index_header_background">
    <h1 id="index_title">B L O G</h1>
  <div>
<% if session[:admin] == true %>
<div class='container'>
  <div id="blog_index_admin_options">
      <%= link_to "Create Blog Post", new_blog_path, class: 'index_link_to_button' %>
      <%= link_to "Log Out", end_session_path, class: 'index_link_to_button' %>
  </div>
  <!-- ADMIN -->
  <div class='container'><%= will_paginate @blogs %></div>
  <% @blogs.each do |blog|%>
  <div id="blog_index_contents">
  <!-- ADMIN TEST -->
  <div class="container">
    <div id='blog_image_container'>
      <div id="blog_image_left">
        <% if blog.image? %>
          <div class='blog_image_index' style='background-image: url(<%= blog.image.blog_index %>); background-size: cover;background-position: center;'></div>
        <% else %>
          <div class='blog_image_index' style='background-image: url(/assets/findyou.jpg); background-size: cover;background-position: center;'></div>
        <% end %>
      </div>
      <div id="blog_text_preview">
       <h2 id='blog_index_title_preview'><%= link_to sanitize(blog.title), blog_path(blog.id) %></h2>
         <p class='index_blog_date'>
           <%=blog.created_at.strftime("%B %-d, %Y")%>
         </p>
           <%= (sanitize "\"#{strip_tags(blog.body)}\"").truncate(500, :escape => false) %>
           <%= link_to "Continue", blog_path(blog.id), class: "blog_index_read_more" %>
      </div>
    </div>
    <!-- END ADMIN TEST -->
        <div id='blog_edit_options'>
            <%= link_to "Edit", edit_blog_path(blog.id), class: 'index_link_to_button' %>
            <%= link_to "Delete", blog_path(blog.id), method: :delete, class: 'index_link_to_button' %>
        </div>
    <% end %>
  </div>

<!-- USER -->
<% else %>
  <div class='container' style="padding-top: 40px;">
    <%= will_paginate @blogs %>
    <% @blogs.each do |blog|%>
<!-- USER TEST -->
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-4 col-12">
        <% if blog.image? %>
          <a href="/blog/<%= blog.id %>">
            <div style='background-image: url(<%= blog.image.blog_index %>);background-size: cover;background-position: center; height: 275px;width: 100%;'></div>
          </a>
        <% else %>
         <a href="/blog/<%= blog.id %>">
          <div style='background-image: url( /assets/findyou.jpg);background-size: cover;background-position: center;height: 275px;width: 100%;'></div>
          </a>
        <% end %>
      </div>
      <div class="col-lg-8 col-md-8 col-12">
        <h2><%= link_to sanitize(blog.title), blog_path(blog.id), class: "edit_tag blog_index_title_preview" %></h2>
          <p class="index_blog_date" ">
            <%=blog.created_at.strftime("%B")%> <%=blog.created_at.strftime("%-d")%>, <%=blog.created_at.strftime("%Y")%>
          </p>
          <p style="font-family: 'Muli',sans-serif">
          <span style="color: #64615F">
          <%= (sanitize "\"#{strip_tags(blog.body)}\"").truncate(600, :escape => false) %>
          </span>
          <span class="blog_index_read_more">
          <%= link_to "Continue", blog_path(blog.id), class: "blog_index_read_more"%>
          </span>
          </p>


      </div>
    </div>
      </br>
        </br>
          </br>
  </div>
    <% end %>
  <% end %>
<!-- END USER TEST -->
  <div id='blog_log_in_link_container'>
    <%= link_to "Author Log In", password_input_path %>
  </div>
</body>

app/views/blog/new.html.erb
<script src="https://cdn.ckeditor.com/ckeditor5/10.0.1/classic/ckeditor.js"></script>
<!-- Resources for ckeditor -->
<!-- http://www.dailysmarty.com/posts/how-to-integrate-ckeditor-into-a-rails-5-application -->
<!-- https://github.com/galetahub/ckeditor -->

<div id="new_blog_form_container">
  <h1>Create New Blog Post:</h1>
  <div id="new_blog_form">
        <%= form_for @blog, url: {action: "create"} do |f| %>
            <div id='edit_blog_form_section'>
              <%= f.label :image %>
              <%= f.file_field :image %>
              <p>Images should be 1200 x 400 at minimum to prevent blurryness.</p>
            </div>
            <div id='new_blog_form_section'>
                <%= f.label :title %>
                <%= f.cktext_area :title %>
            </div>
            <div id='new_blog_form_section'>
                <%= f.label :body %>
                <%= f.cktext_area :body %>
            </div>
            <div id='new_blog_form_section'>
                <%= f.submit "Create new post", id: "new_blog_form_button" %>
            </div>
        <% end %>
    </div>
</div>

<script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
    } );
</script>

app/views/blog/password_input.html.erb
<div id='password_blog_container'>
      <div id='password_blog_form_continer'>
            <%= form_for :input, url: '/password_authenticate', method: 'post' do |f| %>
            <div class='password_blog_form_section'>
                  <%= f.label :password, id: 'password_blog_form_title' %>
            </div>
            <div class='password_blog_form_section'>
                  <%= f.password_field :password, id: 'password_blog_form_text_field'  %>
            </div>
            <div class='password_blog_form_section'>
                  <%= f.submit 'Submit', id: 'password_blog_form_submit' %>
            </div>
            <% end %>
      </div>
</div>

app/views/blog/show.html.erb
<body style="background-color: #f6f6f6">
<div class='blog_show'>
  <% if @blog.image? %>
    <div class='blog_image_show' style='background-image: url(<%= @blog.image.large %>);background-size: cover;background-position: center;'>
  <% else %>
    <div class='blog_image_show' style='background-image: url(/assets/findyou.jpg);background-size: cover;background-position: center;'>
  <% end %>
    <h1 class='text-center blog_title_show'><%= sanitize @blog.title %></h1>
    </div>
  <div class='container' style="background-color: white; position: relative;top:-40px;">
    <h4 class='text-center' style='padding-top: 30px;'> <%=@blog.created_at.strftime("%B")%> <%=@blog.created_at.strftime("%-d")%>, <%=@blog.created_at.strftime("%Y")%> </h4>
    <div class='container'>
      <%= sanitize @blog.body %>
    </div>
    <%= render partial: "social" %>
    <div class='blog_index_selection_options'>
      <% if @blog.previous.presence %>
        <%= link_to "Previous", blog_path(@blog.previous), class: 'index_link_to_button' %>
      <% end %>
        <%= link_to "Blogs Home", blog_index_path, class: 'index_link_to_button' %>
      <% if @blog.next.presence %>
        <%= link_to "Next", blog_path(@blog.next), class: 'index_link_to_button' %>
      <% end %>
    </div>
  </div>
</div>
</body>